### ISSUE TITLE
Roadmap Items Delayed

### ISSUE THREAD

**Issue by migheljackson** [CityOfLearning/public#1]
The Org Dashboard v1.1, Org Dashboard v1.2, and Partner API deliverable dates have been delayed.  The revised delivery dates are as follows:

- Org Dashboard v1.1: 2/20/2015
- Org Dashboard v1.2: 3/2/2015

Partner API will be split into two deliverables
- Partner API v1.1: 3/6/2015
- Partner API v1.2: 3/20/2015

The roadmap will be revised shortly to reflect the changed timeline and to reflect current progress towards completion of each item.

**Comment by remixlearning** [comment]
Everyone, I updated the roadmap to reflect these dates. 

(Sorry for the permissions delay @migheljackson )

**Comment by timothyfcook** [comment]
Seems like we should reserve the use of the Issues function on the Repo for issues with the repo, can we get a different place for discussions and to share updates?

**Comment by migheljackson** [comment]
Yes, we may be using the term "Issue" loosely, but since this is serving as the primary platform documentation repo, we want to keep any discussions and updates about the platform here so that the relevant documentation can be easily referenced.  We can use labels to further delineate the types of posts.
